spring:
  application:
    name: content-service
  datasource:
    url: jdbc:mysql://localhost:3306/content_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MyDQLDialect

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info
